/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_binduv_libuv_handles_Libuv */

#ifndef _Included_com_binduv_libuv_handles_Libuv
#define _Included_com_binduv_libuv_handles_Libuv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_binduv_libuv_handles_Libuv
 * Method:    uv_err_name
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_binduv_libuv_handles_Libuv_uv_1err_1name
        (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
