/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_binduv_libuv_handles_Async */

#ifndef _Included_com_binduv_libuv_handles_Async
#define _Included_com_binduv_libuv_handles_Async
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_binduv_libuv_handles_Async
 * Method:    uv_async_init
 * Signature: (JJLjava/lang/Runnable;)I
 */
JNIEXPORT jint JNICALL Java_com_binduv_libuv_handles_Async_uv_1async_1init
        (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     com_binduv_libuv_handles_Async
 * Method:    uv_async_send
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_binduv_libuv_handles_Async_uv_1async_1send
        (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
