/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_binduv_libuv_handles_UvHandle */

#ifndef _Included_com_binduv_libuv_handles_UvHandle
#define _Included_com_binduv_libuv_handles_UvHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_binduv_libuv_handles_UvHandle
 * Method:    uv_handle_init
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_binduv_libuv_handles_UvHandle_uv_1handle_1init
        (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
