/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_binduv_libuv_handles_AsyncHandle */

#ifndef _Included_com_binduv_libuv_handles_AsyncHandle
#define _Included_com_binduv_libuv_handles_AsyncHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_binduv_libuv_handles_AsyncHandle
 * Method:    uv_async_init
 * Signature: (JJLjava/lang/Runnable;)I
 */
JNIEXPORT jint JNICALL Java_com_binduv_libuv_handles_AsyncHandle_uv_1async_1init
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     com_binduv_libuv_handles_AsyncHandle
 * Method:    uv_async_send
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_binduv_libuv_handles_AsyncHandle_uv_1async_1send
        (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
